FROM node:22-alpine
WORKDIR /usr/src

RUN corepack enable && corepack prepare pnpm@10.18.1 --activate

COPY pnpm-lock.yaml pnpm-workspace.yaml package.json tsconfig.base.json ./
COPY common/package.json common/
COPY db/orm/package.json db/orm/
COPY apps/movie-recommendation-app/package.json apps/movie-recommendation-app/
RUN pnpm install --filter @app/movie-recommendation-app... --frozen-lockfile

COPY . .

EXPOSE 3000
CMD ["pnpm", "--filter", "@app/movie-recommendation-app", "dev"]
