FROM node:22-alpine
WORKDIR /usr/src

COPY package*.json ./
COPY tsconfig.base.json ./
COPY common/package*.json common/
COPY apps/movie-recommendation-app/package*.json apps/movie-recommendation-app/
RUN npm install

COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev", "--workspace=@app/movie-recommendation-app"]
