FROM node:22-alpine
WORKDIR /usr/src

COPY package*.json ./
COPY tsconfig.base.json ./
COPY common/package*.json common/
COPY db/package*.json db/
COPY apps/main-app/package*.json apps/main-app/
RUN npm install

COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev", "--workspace=@app/main-app"]
